import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CountriesServiceService {

  constructor() { }


  private countries: { key: string, value: string }[] = [
    { key: "Afghanistan", value: "Afghanistan" },
    { key: "Åland Islands", value: "Åland Islands" },
    { key: "Albania", value: "Albania" },
    { key: "Algeria", value: "Algeria" },
    { key: "American Samoa", value: "American Samoa" },
    { key: "Andorra", value: "Andorra" },
    { key: "Angola", value: "Angola" },
    { key: "Anguilla", value: "Anguilla" },
    { key: "Antigua & Barbuda", value: "Antigua & Barbuda" },
    { key: "Argentina", value: "Argentina" },
    { key: "Armenia", value: "Armenia" },
    { key: "Aruba", value: "Aruba" },
    { key: "Australia", value: "Australia" },
    { key: "Austria", value: "Austria" },
    { key: "Azerbaijan", value: "Azerbaijan" },
    { key: "Bahamas", value: "Bahamas" },
    { key: "Bahrain", value: "Bahrain" },
    { key: "Bangladesh", value: "Bangladesh" },
    { key: "Barbados", value: "Barbados" },
    { key: "Belarus", value: "Belarus" },
    { key: "Belgium", value: "Belgium" },
    { key: "Belize", value: "Belize" },
    { key: "Benin", value: "Benin" },
    { key: "Bermuda", value: "Bermuda" },
    { key: "Bhutan", value: "Bhutan" },
    { key: "Bolivia", value: "Bolivia" },
    { key: "Bosnia & Herzegovina", value: "Bosnia & Herzegovina" },
    { key: "Botswana", value: "Botswana" },
    { key: "Brazil", value: "Brazil" },
    { key: "British Indian Ocean Territory", value: "British Indian Ocean Territory" },
    { key: "British Virgin Islands", value: "British Virgin Islands" },
    { key: "Brunei", value: "Brunei" },
    { key: "Bulgaria", value: "Bulgaria" },
    { key: "Burkina Faso", value: "Burkina Faso" },
    { key: "Burundi", value: "Burundi" },
    { key: "Cambodia", value: "Cambodia" },
    { key: "Cameroon", value: "Cameroon" },
    { key: "Canada", value: "Canada" },
    { key: "Cape Verde", value: "Cape Verde" },
    { key: "Bonaire, Sint Eustatius and Saba", value: "Bonaire, Sint Eustatius and Saba" },
    { key: "Cayman Islands", value: "Cayman Islands" },
    { key: "Central African Republic", value: "Central African Republic" },
    { key: "Chad", value: "Chad" },
    { key: "Chile", value: "Chile" },
    { key: "China", value: "China" },
    { key: "Christmas Island", value: "Christmas Island" },
    { key: "Cocos (Keeling) Islands", value: "Cocos (Keeling) Islands" },
    { key: "Colombia", value: "Colombia" },
    { key: "Comoros", value: "Comoros" },
    { key: "Congo", value: "Congo" },
    { key: "Cook Islands", value: "Cook Islands" },
    { key: "Costa Rica", value: "Costa Rica" },
    { key: "Croatia", value: "Croatia" },
    { key: "Cuba", value: "Cuba" },
    { key: "Curaçao", value: "Curaçao" },
    { key: "Cyprus", value: "Cyprus" },
    { key: "Czechia", value: "Czechia" },
    { key: "Democratic Republic of the Congo", value: "Democratic Republic of the Congo" },
    { key: "Denmark", value: "Denmark" },
    { key: "Djibouti", value: "Djibouti" },
    { key: "Dominica", value: "Dominica" },
    { key: "Dominican Republic", value: "Dominican Republic" },
    { key: "Timor-Leste", value: "Timor-Leste" },
    { key: "Ecuador", value: "Ecuador" },
    { key: "Egypt", value: "Egypt" },
    { key: "El Salvador", value: "El Salvador" },
    { key: "Equatorial Guinea", value: "Equatorial Guinea" },
    { key: "Eritrea", value: "Eritrea" },
    { key: "Estonia", value: "Estonia" },
    { key: "Ethiopia", value: "Ethiopia" },
    { key: "Falkland Islands (Islas Malvinas)", value: "Falkland Islands (Islas Malvinas)" },
    { key: "Faroe Islands", value: "Faroe Islands" },
    { key: "Fiji", value: "Fiji" },
    { key: "Finland", value: "Finland" },
    { key: "France", value: "France" },
    { key: "French Guiana", value: "French Guiana" },
    { key: "French Polynesia", value: "French Polynesia" },
    { key: "Gabon", value: "Gabon" },
    { key: "Gambia", value: "Gambia" },
    { key: "Georgia", value: "Georgia" },
    { key: "Germany", value: "Germany" },
    { key: "Ghana", value: "Ghana" },
    { key: "Gibraltar", value: "Gibraltar" },
    { key: "Greece", value: "Greece" },
    { key: "Greenland", value: "Greenland" },
    { key: "Grenada", value: "Grenada" },
    { key: "Guadeloupe", value: "Guadeloupe" },
    { key: "Guam", value: "Guam" },
    { key: "Guatemala", value: "Guatemala" },
    { key: "Guernsey", value: "Guernsey" },
    { key: "Guinea", value: "Guinea" },
    { key: "Guinea-Bissau", value: "Guinea-Bissau" },
    { key: "Guyana", value: "Guyana" },
    { key: "Haiti", value: "Haiti" },
    { key: "Honduras", value: "Honduras" },
    { key: "Hong Kong", value: "Hong Kong" },
    { key: "Hungary", value: "Hungary" },
    { key: "Iceland", value: "Iceland" },
    { key: "India", value: "India" },
    { key: "Indonesia", value: "Indonesia" },
    { key: "Iraq", value: "Iraq" },
    { key: "Ireland", value: "Ireland" },
    { key: "Isle of Man", value: "Isle of Man" },
    { key: "Israel", value: "Israel" },
    { key: "Italy", value: "Italy" },
    { key: "Côte d’Ivoire", value: "Côte d’Ivoire" },
    { key: "Jamaica", value: "Jamaica" },
    { key: "Japan", value: "Japan" },
    { key: "Jersey", value: "Jersey" },
    { key: "Jordan", value: "Jordan" },
    { key: "Kazakhstan", value: "Kazakhstan" },
    { key: "Kenya", value: "Kenya" },
    { key: "Kiribati", value: "Kiribati" },
    { key: "Kosovo", value: "Kosovo" },
    { key: "Kuwait", value: "Kuwait" },
    { key: "Kyrgyzstan", value: "Kyrgyzstan" },
    { key: "Laos", value: "Laos" },
    { key: "Latvia", value: "Latvia" },
    { key: "Lebanon", value: "Lebanon" },
    { key: "Lesotho", value: "Lesotho" },
    { key: "Liberia", value: "Liberia" },
    { key: "Libya", value: "Libya" },
    { key: "Liechtenstein", value: "Liechtenstein" },
    { key: "Lithuania", value: "Lithuania" },
    { key: "Luxembourg", value: "Luxembourg" },
    { key: "Macau", value: "Macau" },
    { key: "North Macedonia", value: "North Macedonia" },
    { key: "Madagascar", value: "Madagascar" },
    { key: "Malawi", value: "Malawi" },
    { key: "Malaysia", value: "Malaysia" },
    { key: "Maldives", value: "Maldives" },
    { key: "Mali", value: "Mali" },
    { key: "Malta", value: "Malta" },
    { key: "Marshall Islands", value: "Marshall Islands" },
    { key: "Martinique", value: "Martinique" },
    { key: "Mauritania", value: "Mauritania" },
    { key: "Mauritius", value: "Mauritius" },
    { key: "Mayotte", value: "Mayotte" },
    { key: "Mexico", value: "Mexico" },
    { key: "Micronesia", value: "Micronesia" },
    { key: "Moldova", value: "Moldova" },
    { key: "Monaco", value: "Monaco" },
    { key: "Mongolia", value: "Mongolia" },
    { key: "Montenegro", value: "Montenegro" },
    { key: "Montserrat", value: "Montserrat" },
    { key: "Morocco", value: "Morocco" },
    { key: "Mozambique", value: "Mozambique" },
    { key: "Myanmar", value: "Myanmar" },
    { key: "Namibia", value: "Namibia" },
    { key: "Nauru", value: "Nauru" },
    { key: "Nepal", value: "Nepal" },
    { key: "Netherlands", value: "Netherlands" },
    { key: "New Caledonia", value: "New Caledonia" },
    { key: "New Zealand", value: "New Zealand" },
    { key: "Nicaragua", value: "Nicaragua" },
    { key: "Niger", value: "Niger" },
    { key: "Nigeria", value: "Nigeria" },
    { key: "Niue", value: "Niue" },
    { key: "Norfolk Island", value: "Norfolk Island" },
    { key: "Northern Mariana Islands", value: "Northern Mariana Islands" },
    { key: "Norway", value: "Norway" },
    { key: "Oman", value: "Oman" },
    { key: "Pakistan", value: "Pakistan" },
    { key: "Palau", value: "Palau" },
    { key: "Palestinian Territories", value: "Palestinian Territories" },
    { key: "Panama", value: "Panama" },
    { key: "Papua New Guinea", value: "Papua New Guinea" },
    { key: "Paraguay", value: "Paraguay" },
    { key: "Peru", value: "Peru" },
    { key: "Philippines", value: "Philippines" },
    { key: "Pitcairn Islands", value: "Pitcairn Islands" },
    { key: "Poland", value: "Poland" },
    { key: "Portugal", value: "Portugal" },
    { key: "Puerto Rico", value: "Puerto Rico" },
    { key: "Qatar", value: "Qatar" },
    { key: "Réunion", value: "Réunion" },
    { key: "Romania", value: "Romania" },
    { key: "Russia", value: "Russia" },
    { key: "Rwanda", value: "Rwanda" },
    { key: "St. Barthélemy", value: "St. Barthélemy" },
    { key: "St. Helena", value: "St. Helena" },
    { key: "St. Kitts & Nevis", value: "St. Kitts & Nevis" },
    { key: "St. Lucia", value: "St. Lucia" },
    { key: "St. Martin", value: "St. Martin" },
    { key: "St. Pierre & Miquelon", value: "St. Pierre & Miquelon" },
    { key: "St. Vincent & the Grenadines", value: "St. Vincent & the Grenadines" },
    { key: "Samoa", value: "Samoa" },
    { key: "San Marino", value: "San Marino" },
    { key: "São Tomé & Príncipe", value: "São Tomé & Príncipe" },
    { key: "Saudi Arabia", value: "Saudi Arabia" },
    { key: "Senegal", value: "Senegal" },
    { key: "Serbia", value: "Serbia" },
    { key: "Seychelles", value: "Seychelles" },
    { key: "Sierra Leone", value: "Sierra Leone" },
    { key: "Singapore", value: "Singapore" },
    { key: "Sint Maarten", value: "Sint Maarten" },
    { key: "Slovakia", value: "Slovakia" },
    { key: "Slovenia", value: "Slovenia" },
    { key: "Solomon Islands", value: "Solomon Islands" },
    { key: "Somalia", value: "Somalia" },
    { key: "South Africa", value: "South Africa" },
    { key: "South Georgia & the South Sandwich Islands", value: "South Georgia & the South Sandwich Islands" },
    { key: "South Korea", value: "South Korea" },
    { key: "South Sudan", value: "South Sudan" },
    { key: "Spain", value: "Spain" },
    { key: "Sri Lanka", value: "Sri Lanka" },
    { key: "Sudan", value: "Sudan" },
    { key: "Suriname", value: "Suriname" },
    { key: "Svalbard & Jan Mayen", value: "Svalbard & Jan Mayen" },
    { key: "Eswatini", value: "Eswatini" },
    { key: "Sweden", value: "Sweden" },
    { key: "Switzerland", value: "Switzerland" },
    { key: "Taiwan", value: "Taiwan" },
    { key: "Tajikistan", value: "Tajikistan" },
    { key: "Tanzania", value: "Tanzania" },
    { key: "Thailand", value: "Thailand" },
    { key: "Togo", value: "Togo" },
    { key: "Tokelau", value: "Tokelau" },
    { key: "Tonga", value: "Tonga" },
    { key: "Trinidad & Tobago", value: "Trinidad & Tobago" },
    { key: "Tunisia", value: "Tunisia" },
    { key: "Turkey", value: "Turkey" },
    { key: "Turkmenistan", value: "Turkmenistan" },
    { key: "Turks & Caicos Islands", value: "Turks & Caicos Islands" },
    { key: "Tuvalu", value: "Tuvalu" },
    { key: "U.S. Virgin Islands", value: "U.S. Virgin Islands" },
    { key: "Uganda", value: "Uganda" },
    { key: "Ukraine", value: "Ukraine" },
    { key: "United Arab Emirates", value: "United Arab Emirates" },
    { key: "United Kingdom", value: "United Kingdom" },
    { key: "United States", value: "United States" },
    { key: "Uruguay", value: "Uruguay" },
    { key: "Uzbekistan", value: "Uzbekistan" },
    { key: "Vanuatu", value: "Vanuatu" },
    { key: "Vatican City", value: "Vatican City" },
    { key: "Venezuela", value: "Venezuela" },
    { key: "Vietnam", value: "Vietnam" },
    { key: "Wallis & Futuna", value: "Wallis & Futuna" },
    { key: "Western Sahara", value: "Western Sahara" },
    { key: "Yemen", value: "Yemen" },
    { key: "Zambia", value: "Zambia" },
    { key: "Zimbabwe", value: "Zimbabwe" }
  ];

  getCountries(): { key: string, value: string }[] {
    return this.countries;
  }
}
