import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CountriesServiceService {
  constructor() {}

  private countries: { name: string }[] = [
    { name: "Afghanistan" },
    { name: "Åland Islands" },
    { name: "Albania" },
    { name: "Algeria" },
    { name: "American Samoa" },
    { name: "Andorra" },
    { name: "Angola" },
    { name: "Anguilla" },
    { name: "Antigua & Barbuda" },
    { name: "Argentina" },
    { name: "Armenia" },
    { name: "Aruba" },
    { name: "Australia" },
    { name: "Austria" },
    { name: "Azerbaijan" },
    { name: "Bahamas" },
    { name: "Bahrain" },
    { name: "Bangladesh" },
    { name: "Barbados" },
    { name: "Belarus" },
    { name: "Belgium" },
    { name: "Belize" },
    { name: "Benin" },
    { name: "Bermuda" },
    { name: "Bhutan" },
    { name: "Bolivia" },
    { name: "Bosnia & Herzegovina" },
    { name: "Botswana" },
    { name: "Brazil" },
    { name: "British Indian Ocean Territory" },
    { name: "British Virgin Islands" },
    { name: "Brunei" },
    { name: "Bulgaria" },
    { name: "Burkina Faso" },
    { name: "Burundi" },
    { name: "Cambodia" },
    { name: "Cameroon" },
    { name: "Canada" },
    { name: "Cape Verde" },
    { name: "Bonaire, Sint Eustatius and Saba" },
    { name: "Cayman Islands" },
    { name: "Central African Republic" },
    { name: "Chad" },
    { name: "Chile" },
    { name: "China" },
    { name: "Christmas Island" },
    { name: "Cocos (Keeling) Islands" },
    { name: "Colombia" },
    { name: "Comoros" },
    { name: "Congo" },
    { name: "Cook Islands" },
    { name: "Costa Rica" },
    { name: "Croatia" },
    { name: "Cuba" },
    { name: "Curaçao" },
    { name: "Cyprus" },
    { name: "Czechia" },
    { name: "Democratic Republic of the Congo" },
    { name: "Denmark" },
    { name: "Djibouti" },
    { name: "Dominica" },
    { name: "Dominican Republic" },
    { name: "Timor-Leste" },
    { name: "Ecuador" },
    { name: "Egypt" },
    { name: "El Salvador" },
    { name: "Equatorial Guinea" },
    { name: "Eritrea" },
    { name: "Estonia" },
    { name: "Ethiopia" },
    { name: "Falkland Islands (Islas Malvinas)" },
    { name: "Faroe Islands" },
    { name: "Fiji" },
    { name: "Finland" },
    { name: "France" },
    { name: "French Guiana" },
    { name: "French Polynesia" },
    { name: "Gabon" },
    { name: "Gambia" },
    { name: "Georgia" },
    { name: "Germany" },
    { name: "Ghana" },
    { name: "Gibraltar" },
    { name: "Greece" },
    { name: "Greenland" },
    { name: "Grenada" },
    { name: "Guadeloupe" },
    { name: "Guam" },
    { name: "Guatemala" },
    { name: "Guernsey" },
    { name: "Guinea" },
    { name: "Guinea-Bissau" },
    { name: "Guyana" },
    { name: "Haiti" },
    { name: "Honduras" },
    { name: "Hong Kong" },
    { name: "Hungary" },
    { name: "Iceland" },
    { name: "India" },
    { name: "Indonesia" },
    { name: "Iraq" },
    { name: "Ireland" },
    { name: "Isle of Man" },
    { name: "Italy" },
    { name: "Côte d’Ivoire" },
    { name: "Jamaica" },
    { name: "Japan" },
    { name: "Jersey" },
    { name: "Jordan" },
    { name: "Kazakhstan" },
    { name: "Kenya" },
    { name: "Kiribati" },
    { name: "Kosovo" },
    { name: "Kuwait" },
    { name: "Kyrgyzstan" },
    { name: "Laos" },
    { name: "Latvia" },
    { name: "Lebanon" },
    { name: "Lesotho" },
    { name: "Liberia" },
    { name: "Libya" },
    { name: "Liechtenstein" },
    { name: "Lithuania" },
    { name: "Luxembourg" },
    { name: "Macau" },
    { name: "North Macedonia" },
    { name: "Madagascar" },
    { name: "Malawi" },
    { name: "Malaysia" },
    { name: "Maldives" },
    { name: "Mali" },
    { name: "Malta" },
    { name: "Marshall Islands" },
    { name: "Martinique" },
    { name: "Mauritania" },
    { name: "Mauritius" },
    { name: "Mayotte" },
    { name: "Mexico" },
    { name: "Micronesia" },
    { name: "Moldova" },
    { name: "Monaco" },
    { name: "Mongolia" },
    { name: "Montenegro" },
    { name: "Montserrat" },
    { name: "Morocco" },
    { name: "Mozambique" },
    { name: "Myanmar" },
    { name: "Namibia" },
    { name: "Nauru" },
    { name: "Nepal" },
    { name: "Netherlands" },
    { name: "New Caledonia" },
    { name: "New Zealand" },
    { name: "Nicaragua" },
    { name: "Niger" },
    { name: "Nigeria" },
    { name: "Niue" },
    { name: "Norfolk Island" },
    { name: "Northern Mariana Islands" },
    { name: "Norway" },
    { name: "Oman" },
    { name: "Pakistan" },
    { name: "Palau" },
    { name: "Palestinian Territories" },
    { name: "Panama" },
    { name: "Papua New Guinea" },
    { name: "Paraguay" },
    { name: "Peru" },
    { name: "Philippines" },
    { name: "Pitcairn Islands" },
    { name: "Poland" },
    { name: "Portugal" },
    { name: "Puerto Rico" },
    { name: "Qatar" },
    { name: "Réunion" },
    { name: "Romania" },
    { name: "Russia" },
    { name: "Rwanda" },
    { name: "St. Barthélemy" },
    { name: "St. Helena" },
    { name: "St. Kitts & Nevis" },
    { name: "St. Lucia" },
    { name: "St. Martin" },
    { name: "St. Pierre & Miquelon" },
    { name: "St. Vincent & the Grenadines" },
    { name: "Samoa" },
    { name: "San Marino" },
    { name: "São Tomé & Príncipe" },
    { name: "Saudi Arabia" },
    { name: "Senegal" },
    { name: "Serbia" },
    { name: "Seychelles" },
    { name: "Sierra Leone" },
    { name: "Singapore" },
    { name: "Sint Maarten" },
    { name: "Slovakia" },
    { name: "Slovenia" },
    { name: "Solomon Islands" },
    { name: "Somalia" },
    { name: "South Africa" },
    { name: "South Georgia & the South Sandwich Islands" },
    { name: "South Korea" },
    { name: "South Sudan" },
    { name: "Spain" },
    { name: "Sri Lanka" },
    { name: "Sudan" },
    { name: "Suriname" },
    { name: "Svalbard & Jan Mayen" },
    { name: "Eswatini" },
    { name: "Sweden" },
    { name: "Switzerland" },
    { name: "Taiwan" },
    { name: "Tajikistan" },
    { name: "Tanzania" },
    { name: "Thailand" },
    { name: "Togo" },
    { name: "Tokelau" },
    { name: "Tonga" },
    { name: "Trinidad & Tobago" },
    { name: "Tunisia" },
    { name: "Turkey" },
    { name: "Turkmenistan" },
    { name: "Turks & Caicos Islands" },
    { name: "Tuvalu" },
    { name: "U.S. Virgin Islands" },
    { name: "Uganda" },
    { name: "Ukraine" },
    { name: "United Arab Emirates" },
    { name: "United Kingdom" },
    { name: "United States" },
    { name: "Uruguay" },
    { name: "Uzbekistan" },
    { name: "Vanuatu" },
    { name: "Vatican City" },
    { name: "Venezuela" },
    { name: "Vietnam" },
    { name: "Wallis & Futuna" },
    { name: "Western Sahara" },
    { name: "Yemen" },
    { name: "Zambia" },
    { name: "Zimbabwe" }
  ];

  getCountries(): { name: string }[] {
    return this.countries;
  }
}